# Generated by Django 5.1 on 2024-09-01 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('国', '国語'), ('数', '数学'), ('英', '英語'), ('理', '理科'), ('社', '社会')], max_length=2)),
                ('priority', models.IntegerField(choices=[(1, '★☆☆ (低い)'), (2, '★★☆ (中くらい)'), (3, '★★★ (高い)')], default=2)),
                ('subtitle1', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle1_completed', models.BooleanField(default=False)),
                ('subtitle2', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle2_completed', models.BooleanField(default=False)),
                ('subtitle3', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle3_completed', models.BooleanField(default=False)),
                ('subtitle4', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle4_completed', models.BooleanField(default=False)),
                ('subtitle5', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle5_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('国', '国語'), ('数', '数学'), ('英', '英語'), ('理', '理科'), ('社', '社会')], max_length=2)),
                ('priority', models.IntegerField(choices=[(1, '★☆☆ (低い)'), (2, '★★☆ (中くらい)'), (3, '★★★ (高い)')], default=2)),
                ('subtitle1', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle2', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle3', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle4', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle5', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
